Updating Portuguese translation
sitomani/4champ pull request #31
Opened 2024-02-02 21:03 UTC by rnbastos

2024-02-05 18:27 UTC, sitomani commented
Thanks for the translations! This looks good except for one dropped text `AboutView_Search` is still in english. Please fix that and we're ready for merge.

2024-02-05 18:28 UTC, sitomani requested changes
see comments.

2024-02-05 18:45 UTC, rnbastos commented
Small fixes...

2024-02-07 14:14 UTC, sitomani approved these changes

2024-02-07 14:15 UTC, merged